export default [
  {
    files: ['assets/js/**/*.js'],
    languageOptions: {
      ecmaVersion: 2021,
      sourceType: 'script',
      globals: {
        document: 'readonly',
        window: 'readonly',
        console: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        fetch: 'readonly',
        navigator: 'readonly',
        location: 'readonly',
        history: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        IntersectionObserver: 'readonly',
        MutationObserver: 'readonly',
        ResizeObserver: 'readonly',
        WheelEvent: 'readonly',
        Node: 'readonly',
        NodeFilter: 'readonly',
        Text: 'readonly',
        ShadowRoot: 'readonly',
        DocumentFragment: 'readonly',
        Element: 'readonly',
        HTMLElement: 'readonly',
        Event: 'readonly',
        CustomEvent: 'readonly',
        FormData: 'readonly',
        performance: 'readonly',
        getComputedStyle: 'readonly',
        Image: 'readonly',
      },
    },
    rules: {
      'no-debugger': 'error',
      'no-alert': 'warn',
      'no-console': 'off',
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
      'no-var': 'warn',
      'prefer-const': 'warn',
      'no-redeclare': 'error',
      'no-unreachable': 'error',
      'no-undef': 'error',
    },
  },
  {
    files: ['assets/js/header-weather-sun-scene.js'],
    languageOptions: {
      ecmaVersion: 2021,
      sourceType: 'module',
    },
  },
];
