export default [
  {
    files: ['sw.js', 'sp-push-worker-fb.js'],
    languageOptions: {
      ecmaVersion: 2021,
      sourceType: 'script',
      globals: {
        self: 'readonly',
        caches: 'readonly',
        fetch: 'readonly',
        URL: 'readonly',
        importScripts: 'readonly',
      },
    },
    rules: {
      'no-debugger': 'error',
      'no-redeclare': 'error',
      'no-unreachable': 'error',
      'no-undef': 'error',
    },
  },
  {
    files: ['assets/js/**/*.js'],
    languageOptions: {
      ecmaVersion: 2021,
      sourceType: 'script',
      globals: {
        document: 'readonly',
        window: 'readonly',
        console: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        fetch: 'readonly',
        navigator: 'readonly',
        location: 'readonly',
        history: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        IntersectionObserver: 'readonly',
        MutationObserver: 'readonly',
        ResizeObserver: 'readonly',
        WheelEvent: 'readonly',
        Node: 'readonly',
        NodeFilter: 'readonly',
        Text: 'readonly',
        ShadowRoot: 'readonly',
        DocumentFragment: 'readonly',
        Element: 'readonly',
        HTMLElement: 'readonly',
        Event: 'readonly',
        CustomEvent: 'readonly',
        FormData: 'readonly',
        performance: 'readonly',
        getComputedStyle: 'readonly',
        Image: 'readonly',
      },
    },
    rules: {
      'no-debugger': 'error',
      'no-alert': 'warn',
      'no-console': 'off',
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
      'no-var': 'warn',
      'prefer-const': 'warn',
      'no-redeclare': 'error',
      'no-unreachable': 'error',
      'no-undef': 'error',
    },
  },
  {
    files: ['assets/js/header-weather-sun-scene.js'],
    languageOptions: {
      ecmaVersion: 2021,
      sourceType: 'module',
    },
  },
  {
    files: ['tools/**/*.{js,mjs,cjs}', '3d-weather-codrops-main/scripts/**/*.mjs', 'docs/vendor/obsidian/verify.mjs'],
    ignores: ['tools/_*.mjs', 'tools/ffmpeg/**', 'tools/ffmpeg_extract/**'],
    languageOptions: {
      ecmaVersion: 2025,
      sourceType: 'module',
      globals: {
        AbortController: 'readonly',
        AbortSignal: 'readonly',
        atob: 'readonly',
        Blob: 'readonly',
        Buffer: 'readonly',
        btoa: 'readonly',
        clearImmediate: 'readonly',
        clearInterval: 'readonly',
        clearTimeout: 'readonly',
        console: 'readonly',
        crypto: 'readonly',
        fetch: 'readonly',
        File: 'readonly',
        FormData: 'readonly',
        Headers: 'readonly',
        performance: 'readonly',
        process: 'readonly',
        Request: 'readonly',
        Response: 'readonly',
        setImmediate: 'readonly',
        setInterval: 'readonly',
        setTimeout: 'readonly',
        structuredClone: 'readonly',
        TextDecoder: 'readonly',
        TextEncoder: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        WebSocket: 'readonly',
        // Browser globals belong to serialized Playwright/CDP callbacks in these tools.
        document: 'readonly',
        Element: 'readonly',
        Event: 'readonly',
        getComputedStyle: 'readonly',
        HTMLElement: 'readonly',
        Image: 'readonly',
        innerHeight: 'readonly',
        IntersectionObserver: 'readonly',
        localStorage: 'readonly',
        location: 'readonly',
        MutationObserver: 'readonly',
        navigator: 'readonly',
        Node: 'readonly',
        PointerEvent: 'readonly',
        requestAnimationFrame: 'readonly',
        sessionStorage: 'readonly',
        window: 'readonly',
      },
    },
    rules: {
      'no-debugger': 'error',
      'no-redeclare': 'error',
      'no-unreachable': 'error',
      'no-undef': 'error',
    },
  },
  {
    files: ['tools/**/*.cjs'],
    languageOptions: {
      sourceType: 'commonjs',
      globals: {
        __dirname: 'readonly',
        __filename: 'readonly',
        exports: 'readonly',
        module: 'readonly',
        require: 'readonly',
      },
    },
  },
  {
    files: ['functions/**/*.js', 'workers/**/*.js', 'integrations/google-gateway/**/*.js'],
    languageOptions: {
      ecmaVersion: 2024,
      sourceType: 'module',
      globals: {
        AbortController: 'readonly',
        atob: 'readonly',
        Blob: 'readonly',
        Buffer: 'readonly',
        btoa: 'readonly',
        caches: 'readonly',
        clearInterval: 'readonly',
        clearTimeout: 'readonly',
        console: 'readonly',
        crypto: 'readonly',
        EmailMessage: 'readonly',
        fetch: 'readonly',
        File: 'readonly',
        FormData: 'readonly',
        Headers: 'readonly',
        HTMLRewriter: 'readonly',
        process: 'readonly',
        ReadableStream: 'readonly',
        Request: 'readonly',
        Response: 'readonly',
        setInterval: 'readonly',
        setTimeout: 'readonly',
        structuredClone: 'readonly',
        TextDecoder: 'readonly',
        TextEncoder: 'readonly',
        TransformStream: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
      },
    },
    rules: {
      'no-debugger': 'error',
      'no-redeclare': 'error',
      'no-unreachable': 'error',
      'no-undef': 'error',
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
      'no-var': 'warn',
      'prefer-const': 'warn',
    },
  },
];
