# Import gitignored .dev.vars into 1Password (no value echo).
# Usage: powershell -NoProfile -File tools/op-import-dev-vars.ps1

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
$devVars = Join-Path $root ".dev.vars"
$opEnv = Join-Path $root ".dev.vars.op"
$title = "HUNDESALON_NIKA_SECRETS"

function Get-Op {
  $c = Get-Command op -ErrorAction SilentlyContinue
  if ($c) { return $c.Source }
  $fallback = Join-Path $env:LOCALAPPDATA "bin\op.exe"
  if (Test-Path $fallback) { return $fallback }
  throw "op CLI not found"
}

function Write-Utf8NoBom([string]$path, [string]$text) {
  $enc = New-Object System.Text.UTF8Encoding $false
  [System.IO.File]::WriteAllText($path, $text, $enc)
}

$op = Get-Op
$env:Path = "$(Split-Path $op);$env:Path"

$null = & $op vault list --format json 2>&1
if ($LASTEXITCODE -ne 0) {
  throw "op not authenticated. Unlock 1Password and approve the CLI prompt."
}

if (-not (Test-Path $devVars)) { throw ".dev.vars not found" }

$map = [ordered]@{}
Get-Content $devVars | ForEach-Object {
  $line = $_.Trim()
  if ($line -eq "" -or $line.StartsWith("#")) { return }
  $i = $line.IndexOf("=")
  if ($i -lt 1) { return }
  $k = $line.Substring(0, $i).Trim()
  $v = $line.Substring($i + 1)
  if ($v.StartsWith('"') -and $v.EndsWith('"') -and $v.Length -ge 2) {
    $v = $v.Substring(1, $v.Length - 2)
  }
  if ($k -and $v) { $map[$k] = $v }
}
if ($map.Count -eq 0) { throw ".dev.vars has no valued keys" }

$templateJson = & $op item template get "API Credential"
$template = $templateJson | ConvertFrom-Json
$template.title = $title

$fields = [System.Collections.Generic.List[object]]::new()
foreach ($f in $template.fields) { $fields.Add($f) }
foreach ($k in $map.Keys) {
  $fields.Add([pscustomobject]@{
    id = $k
    type = "CONCEALED"
    label = $k
    value = $map[$k]
  })
}
$template.fields = $fields.ToArray()

$tmp = Join-Path $env:TEMP ("op-hundesalon-" + [guid]::NewGuid().ToString("n") + ".json")
try {
  Write-Utf8NoBom $tmp ($template | ConvertTo-Json -Depth 8 -Compress)

  $existing = & $op item list --format json 2>$null | ConvertFrom-Json
  $hit = @($existing | Where-Object { $_.title -eq $title }) | Select-Object -First 1

  if ($hit) {
    Write-Host "Updating '$title'..."
    & $op item delete $hit.id --archive 2>$null | Out-Null
  }
  Write-Host "Creating '$title' with $($map.Count) fields..."
  & $op item create --template $tmp | Out-Null
  if ($LASTEXITCODE -ne 0) { throw "op item create failed" }
} finally {
  if (Test-Path $tmp) { Remove-Item $tmp -Force -ErrorAction SilentlyContinue }
}

$item = & $op item get $title --format json | ConvertFrom-Json
$vault = $item.vault.name
if (-not $vault) { $vault = "Personal" }

$lines = @(
  "# Generated by tools/op-import-dev-vars.ps1 - do not commit",
  "# op run --env-file=.dev.vars.op -- npm run deploy"
)
foreach ($k in $map.Keys) {
  $lines += "$k=op://$vault/$title/$k"
}
Write-Utf8NoBom $opEnv (($lines -join "`n") + "`n")
Write-Host "Wrote .dev.vars.op (vault=$vault title=$title keys=$($map.Count))"
Write-Host "Deploy: op run --env-file=.dev.vars.op -- npm run deploy"
